TYPO3:
  Flow:
    object:
      excludeClasses:
        'gedmo.*' : ['.*']

    persistence:
      doctrine:
        eventSubscribers:
          - 'Akii\Translatable\TranslatableListener'
        eventListeners:
          -
            events: ['postLoad', 'postPersist', 'preFlush', 'onFlush', 'loadClassMetadata']
            listener: 'Akii\Translatable\TranslatableListener'